FROM registry.fedoraproject.org/fedora-minimal:40
ARG yq_version=4.22.1
ARG version=latest
LABEL \
    org.opencontainers.image.title="utils image for testing renovate update PRs" \
    org.opencontainers.image.version="${version}" \
    org.opencontainers.image.licenses="MIT"
WORKDIR /src
COPY . .
CMD ["bash", "main.sh"]
