FROM registry.fedoraproject.org/fedora-minimal:42
ARG version=latest
LABEL \
    org.opencontainers.image.title="utils image for testing renovate update PRs" \
    org.opencontainers.image.version="${version}" \
    org.opencontainers.image.licenses="MIT"
CMD ["echo", "hello", "world"]
