apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/cqi-stonesoup-test/test-renovate-updates?rev={{revision}}
  labels:
    appstudio.openshift.io/application: test-renovate-updates
    appstudio.openshift.io/component: test-renovate-updates
    pipelines.appstudio.openshift.io/type: build
  name: build-something
  namespace: cqi-tenant
spec:
  pipelineSpec:
    tasks:
    - name: test-renovate-updates
      params:
      - name: image-url
        value: quay.io/mytestworkload/test-renovate-updates:0.1
      - name: rebuild
        value: "false"
      taskRef:
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-utils:0.1@sha256:3570ac367c2b47a38dc82b7fecb2bb814a057249e7de485478722b4dd8b0b15b
        - name: kind
          value: task
        resolver: bundles

    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-init:0.1@sha256:9eeaf7780f3c0414e0263c4dca9fe91bba39b89a0ff19b967d9fe52ace8f5341
        - name: kind
          value: task
      params:
      - name: image-url
        value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
      - name: skip-checks
        value: "false"
    - name: clone
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clone
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-clone:0.1@sha256:f0d2eb9755d6bd4cdce1bd0cd5efb603ac4933a86c1d2e07d29807d17c847932
        - name: kind
          value: task
      runAfter:
      - init
    - name: test
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: test
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-test:0.1@sha256:3380f0e54f113875c876723a76a30e36cf0786d24c4757e851b575ae8caaabf1
        - name: kind
          value: task
      runAfter:
      - clone
    - name: pushdockerfile
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: pushdockerfile
        - name: bundle
          value: "quay.io/mytestworkload/test-renovate-updates-task-pushdockerfile:0.1@sha256:6a086aab8a87a03c9590c8b48df188ec7c391cc892fe1ac5db7459c63eb2d1a5"
        - name: kind
          value: task
        resolver: bundles
    workspaces:
    - name: workspace
