apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/cqi-stonesoup-test/test-renovate-updates?rev={{revision}}
  labels:
    appstudio.openshift.io/application: test-renovate-updates
    appstudio.openshift.io/component: test-renovate-updates
    pipelines.appstudio.openshift.io/type: build
  name: build-something
  namespace: cqi-tenant
spec:
  pipelineSpec:
    tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-init:0.1@sha256:0d80b744eaf8055584ea0d1068c748f44c700dea80f1bfb9946f36cc514d25f7
        - name: kind
          value: task
      params:
      - name: image-url
        value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
      - name: skip-checks
        value: "false"
    - name: clone
      params:
      - name: revision
        value: main
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clone
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-clone:0.1@sha256:5c37db771ac8bcd75dbff9b8922e2e57d534030770ca88cdfed822694ea30931
        - name: kind
          value: task
    - name: test
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: test
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-test:0.1@sha256:a45c49a148149e9d648be9c4c7e8a514b22b2338ddfda0868294311f57907503
        - name: kind
          value: task
    workspaces:
    - name: workspace
