apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: common-build-pipeline
spec:
  tasks:
  - name: init
    params:
    - name: image-url
      value: quay.io/mytestworkload/test-renovate-updates:0.1
    - name: rebuild
      value: "false"
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.1@sha256:72790ec7c0e7ffea4b3c2ace667eac09db8b51c3b87a1a2765cebd950dd84599
      - name: kind
        value: task
      resolver: bundles
