apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: init
  labels:
    app.kubernetes.io/version: "0.7"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
spec:
  params:
    - name: image-url
      description: Image URL for build by PipelineRun
    - name: skip-checks
      description: Skip checks against built image
      default: "true"
  steps:
    - name: init
      image: registry.fedoraproject.org/fedora-minimal:40
      script: |
        echo "This is the initialization task of the build pipeline."
        echo "By default, Checks are skipped to boost the build process."
