#!/usr/bin/env bash

# Known issue:
# - no way to detect whether a migration has been applied or not

# TODO: avoid creating duplicate migration file during current one is being edited.
# TODO: skip creation if pipeline is not changed.

set -euo pipefail

for_task=${1:?Missing task name}
task_file="./tasks/task-${for_task}-0.1.yaml"

if [ ! -e "$task_file" ]; then
    echo "Task file ${task_file} does not exist." >&2
    exit 1
fi

k8s_version=$(yq '.metadata.labels."app.kubernetes.io/version"' "$task_file")

# bump version
IFS=. read -r major minor patch_ <<<"$k8s_version"
if [ -z "$patch_" ]; then
    patch_=1
else
    ((++patch_))
fi
bumped_version="${major}.${minor}.${patch_}"

yq -i ".metadata.labels.\"app.kubernetes.io/version\" |= \"${bumped_version}\"" "$task_file"

./hack/build-and-push.sh -p -d -o /tmp/pl.diff >/dev/null

migration_file="tasks/migrations/task-${for_task}-${bumped_version}.sh"
cat >"$migration_file" <<EOF
#!/usr/bin/env bash
set -euo pipefail
pipeline=\${1?Missing pipeline file}
task_name=${for_task}

# Generated by hack/create-migration.sh. Please review the commands carefully.

EOF

cat /tmp/pl.diff >>"$migration_file"
