apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pushimage
  labels:
    app.kubernetes.io/version: "0.8"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
spec:
  steps:
    - name: push
      image: registry.fedoraproject.org/fedora-minimal:40
      script: |
        echo push image
