apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildimage
  labels:
    app.kubernetes.io/version: "0.2"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
spec:
  results:
    - name: IMAGE_URL
      description: The output image
  steps:
    - name: build
      image: registry.fedoraproject.org/fedora-minimal:40
      script: |
        echo building container image
        OUTPUT_IMAGE=quay.io/mytestworkload/test-renovate-updates:0.1
        echo "$OUTPUT_IMAGE" >$(results.IMAGE_URL.path)
