apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build
  labels:
    "pipelines.openshift.io/used-by": ""
    "pipelines.openshift.io/runtime": ""
    "pipelines.openshift.io/strategy": ""
spec:
  tasks:
    - name: init
      params:
        - name: image-url
          value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
        - name: skip-checks
          value: "false"
      taskRef:
        name: init
    - name: clone
      taskRef:
        name: clone
