apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build
  labels:
    "pipelines.openshift.io/used-by": ""
    "pipelines.openshift.io/runtime": ""
    "pipelines.openshift.io/strategy": ""
spec:
  tasks:
    - name: init
      params:
        - name: image-url
          value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
        - name: skip-checks
          value: "false"
      taskRef:
        name: init
    - name: clone
      params:
        - name: url
          value: https://github.com/cqi-stonesoup-test/test-renovate-updates.git
        - name: revision
          value: release-0.1
      taskRef:
        name: clone
      workspaces:
      - name: source
        workspace: workspace
    - name: test
      params:
      - name: verbose
        value: vv
      taskRef:
        name: test
      runAfter:
        - clone
      workspaces:
      - name: source
        workspace: workspace
    - name: coverage
      taskRef:
        name: coverage
      runAfter:
        - test
        - clone
        - init
      workspaces:
      - name: source
        workspace: workspace
  workspaces:
  - name: workspace
