#!/usr/bin/env bash
set -euo pipefail
pipeline=${1?Missing pipeline file}
task_name=test

# Generated by hack/create-migration.sh. Please review the commands carefully.

yq -i 'del(.spec | .tasks[] | select(.name == "test") | .params[] | select(.name == "include-paths" and .value == "src/"))' "$pipeline"
yq -i '(.spec | .tasks[] | select(.name == "test") | .params) += {"name": "include-paths", "value": "src/"}' "$pipeline"
