apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline-component-b
spec:
  tasks:
  - name: init
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/mytestworkload/test-renovate-updates-task-init:0.1@sha256:4df989432fc2c009a0e6e35dc337597b05baed32547936871486f668be6411da
      - name: kind
        value: task
    params:
    - name: image-url
      value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
    - name: skip-checks
      value: "false"
  - name: clone
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clone
      - name: bundle
        value: quay.io/mytestworkload/test-renovate-updates-task-clone:0.1@sha256:44d5a420073098793e7025250bf102fba83caa09fbca016c708c8ad45f522e27
      - name: kind
        value: task
    params:
    - name: url
      value: "https://github.com/cqi-stonesoup-test/test-renovate-updates.git"
    - name: revision
      value: release-0.1
    - name: url
      value: "https://github.com/cqi-stonesoup-test/test-renovate-updates.git"
    workspaces:
    - name: source
      workspace: workspace
  - name: test
    taskRef:
      params:
      - name: name
        value: test
      - name: bundle
        value: "quay.io/mytestworkload/test-renovate-updates-task-test@sha256:ecf393c8f6fc87a952c9b07473ec303b616b2a944665d7eb1e646466b8cc9319"
      - name: kind
        value: task
      resolver: bundles
    params:
    - name: test_runner
      value: pytest
    - name: verbose
      value: vv
    runAfter:
    - clone
    workspaces:
    - name: source
      workspace: workspace
  - name: coverage
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: coverage
      - name: bundle
        value: quay.io/mytestworkload/test-renovate-updates-task-coverage:0.1@sha256:223678ef9516f4570631a573da5551543899e275c3044f09296d47a3f51bd130
      - name: kind
        value: task
    runAfter:
    - test
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace
