apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/cqi-stonesoup-test/test-renovate-updates?rev={{revision}}
  labels:
    appstudio.openshift.io/application: test-renovate-updates
    appstudio.openshift.io/component: test-renovate-updates
    pipelines.appstudio.openshift.io/type: build
  name: component-a-build-pull-request
  namespace: cqi-tenant
spec:
  pipelineRef:
    name: build-pipeline-component-b
