apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/cqi-stonesoup-test/test-renovate-updates?rev={{revision}}
  labels:
    appstudio.openshift.io/application: test-renovate-updates
    appstudio.openshift.io/component: test-renovate-updates
    pipelines.appstudio.openshift.io/type: build
  name: component-a-build-push
  namespace: cqi-tenant
spec:
  pipelineSpec:
    tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-init:0.1@sha256:4df989432fc2c009a0e6e35dc337597b05baed32547936871486f668be6411da
        - name: kind
          value: task
      params:
      - name: image-url
        value: "quay.io/mytesetworkload/test-renovate-updates-utils:devel"
      - name: skip-checks
        value: "false"
    - name: clone
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clone
        - name: bundle
          value: quay.io/mytestworkload/test-renovate-updates-task-clone:0.1@sha256:44d5a420073098793e7025250bf102fba83caa09fbca016c708c8ad45f522e27
        - name: kind
          value: task
      params:
      - name: url
        value: "https://github.com/cqi-stonesoup-test/test-renovate-updates.git"
      - name: revision
        value: release-0.1
      - name: url
        value: "https://github.com/cqi-stonesoup-test/test-renovate-updates.git"
      workspaces:
      - name: source
        workspace: workspace
    workspaces:
    - name: workspace
